version: "3"
services:
  php-5.6-apache:
    image: phongndq/php:5.6-apache
    ports:
      - 8056:80
      - 44356:443
      - "2256:22"
    volumes:
      - www-data:/home/www-data
    command: bash -c "service ssh start && service apache2 reload & apache2-foreground"
  php-7.0-apache:
    image: phongndq/php:7.0-apache
    ports:
      - 8070:80
      - 44370:443
      - "2270:22"
    volumes:
      - www-data:/home/www-data
    command: bash -c "service ssh start && service apache2 reload & apache2-foreground"
  php-7.2-apache:
    image: phongndq/php:7.2-apache
    ports:
      - 8072:80
      - 44372:80
      - "2272:22"
    volumes:
      - www-data:/home/www-data
    command: bash -c "service ssh start && service apache2 reload & apache2-foreground"
  php-7.4-apache:
    image: phongndq/php:7.4-apache
    ports:
      - 8074:80
      - 44374:443
      - "2274:22"
    volumes:
      - www-data:/home/www-data
    command: bash -c "service ssh start && service apache2 reload & apache2-foreground"
  code-server-3.5.0:
    image: phongndq/code-server:3.5.0
    ports:
      - 8080:8080
    volumes:
       - www-data:/home/www-data
    user: "www-data:www-data"
  elasticsearch-7.6.2:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300 
    environment:
      - ES_PATH_CONF=/home/www-data/elasticsearch-7.6.2/config
      - discovery.type=single-node
    volumes:
      - www-data:/home/www-data
  mysql-5.7:
    image: phongndq/mysql:5.7
    ports:
      - 33057:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1hAI3bOn5sAU
    volumes:
      - www-data:/home/www-data
  mysql-8.0:
    image: phongndq/mysql:8.0
    ports:
      - 33068:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1hAI3bOn5sAU
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - www-data:/home/www-data
  redis-5.0:
    image: redis:5.0
    command: redis-server /home/www-data/redis-5.0/config/redis.conf
    ports:
      - 6379:6379
    volumes:
      - www-data:/home/www-data
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  aspnet-3.5.1:
    image: phongndq/aspnet:3.5.1
    ports:
      - 4099:4099
      - 4199:4199
    volumes:
      - www-data:/home/www-data
    command: "tail -f /dev/null"
volumes:
  www-data:
    external: true